# Generated by Django 4.2.11 on 2024-05-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfProducts',
            fields=[
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('ads_leads', models.BigIntegerField(blank=True, null=True)),
                ('email_leads', models.BigIntegerField(blank=True, null=True)),
                ('refferal_leads', models.BigIntegerField(blank=True, null=True)),
                ('social_media', models.BigIntegerField(blank=True, null=True)),
                ('trade_show_leads', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesAndMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('ads', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('salaries', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('content_creation', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('other_expense', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('total_expense', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('productid', models.ForeignKey(blank=True, db_column='productid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.categoryofproducts')),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('cr_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('productid', models.OneToOneField(blank=True, db_column='productid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.categoryofproducts')),
                ('cost_type', models.CharField(blank=True, max_length=50, null=True)),
                ('distribution_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('logistics_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('administration_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('marketing_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('cost_making_or_buying', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInfo',
            fields=[
                ('transactionid', models.OneToOneField(db_column='transactionid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.transaction')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.usersinfo'),
        ),
    ]
